### ISSUE TITLE
After Ash 3.2.0, rbac resource fails to compile with AddMissingFieldPolicies exception

### ISSUE THREAD

**Issue by sezaru** [traveltechdeluxe/ash-rbac#30]
After upgrading to any Ash version greater than 3.2.0, any resource with ash_rbac that I have fails to compile.

Example:

```elixir
defmodule Core.Accounts.School do
  @moduledoc false

  alias Core.Accounts.School

  use Ash.Resource,
      domain: Core.Accounts,
      data_layer: AshPostgres.DataLayer,
      authorizers: [Ash.Policy.Authorizer],
      extensions: [AshRbac]

  attributes do
    uuid_v7_primary_key :id

    timestamps()
  end

  rbac do
    bypass :admin

    role :teacher do
      actions [:all, :get]

      fields [:*]
    end
  end

  policies do
    alias School.Checks

    policy always() do
      authorize_if Checks.IsConfirmed
    end
  end

  actions do
    defaults [:read]

    read :all do
    end

    read :get do
    end
  end
end
```

This resource will fail with:

```elixir
== Compilation error in file lib/core/accounts/school.ex ==
** (RuntimeError) Exception in transformer Ash.Policy.Authorizer.Transformers.AddMissingFieldPolicies on Core.Accounts.School: 

no case clause matching: nil
    (ash 3.2.0) lib/ash/policy/authorizer/transformers/add_missing_field_policies.ex:16: Ash.Policy.Authorizer.Transformers.AddMissingFieldPolicies.transform/1
    (spark 2.2.10) lib/spark/dsl/extension.ex:590: anonymous fn/4 in Spark.Dsl.Extension.run_transformers/4
    (elixir 1.16.3) lib/enum.ex:4839: Enumerable.List.reduce/3
    (elixir 1.16.3) lib/enum.ex:2582: Enum.reduce_while/3
    (stdlib 5.2.3) erl_eval.erl:746: :erl_eval.do_apply/7
    (stdlib 5.2.3) erl_eval.erl:1026: :erl_eval.expr_list/7
    (stdlib 5.2.3) erl_eval.erl:456: :erl_eval.expr/6
    (stdlib 5.2.3) erl_eval.erl:1026: :erl_eval.expr_list/7
```

If I remove the rbac code block, the resource compiles just fine.

**Comment by barnabasJ** [comment]
I ran into this problem myself today and are actively working on fixing it at the moment

**Comment by barnabasJ** [comment]
A fix is in https://github.com/ash-project/ash/commit/e6d52f2d076ff7cd5ff7ad083cf4ef92fbc8922f and should be released soon
